[pytest]
markers =
    utils: mark a test as a utils test
    embed: mark a test as a embed test
    llm: mark a test as an LLM test
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s - %(levelname)s - %(message)s
asyncio_mode = auto